# ============================================================================
# Name: Heiko Sch채fer (TUXPLAYER)
# Datum: 23. Februar 2026, 06:05
# Beschreibung: GitHub Action zur automatischen Aktualisierung des README
# Zweck: Pr채sentiert Besuchern die neuesten Inhalte von tuxhs.de
# ============================================================================

name: Aktuelle Blogbeitr채ge - Arbeitslauf
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: README mit Blogbeitr채gen aktualisieren
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Musikpfosten ziehen
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST-MUSIC"
          feed_list: "https://tuxhs.de/feed/"

      - name: Pull-Code-Pfosten
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST-CODE"
          feed_list: "https://tuxhs.de/feed/"
