name: Latest Blog Posts Workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write # Das hier ist wichtig f√ºr die Schreibrechte!
    steps:
      - uses: actions/checkout@v3
      - name: Pull Music Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST-MUSIC"
          feed_list: "https://tuxhs.de/category/musik/feed/"
      - name: Pull Code Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST-CODE"
          feed_list: "https://tuxhs.de/category/programmierung/feed/"
